Check format

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -9,6 +9,13 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: '3.x'
 
     - name: Set up Node.js
       uses: actions/setup-node@v2
@@ -23,55 +30,117 @@ jobs:
       run: npm run test
       working-directory: ./backend
 
-    - name: Generate test coverage
-      run: npm run coverage
+    - name: Generate new coverage report
+      run: npm run coverage > coverage_report.txt
       working-directory: ./backend
 
-    - name: Upload coverage report
+    - name: Upload new coverage report
       uses: actions/upload-artifact@v2
       with:
         name: coverage-report
-        path: ./backend/coverage/coverage-final.json
+        path: ./backend/coverage_report.txt
+    
+    - name: Reset to previous commit to get coverage report
+      run: |
+        git reset --hard HEAD~1 
+      working-directory: ./backend
 
-    - name: Download previous coverage report
+    - name: Run tests for previous commit
+      run: npm run test
+      working-directory: ./backend
+
+    - name: Generate previous coverage report
+      run: npm run coverage > coverage_report.txt
+      working-directory: ./backend
+
+    - name: Download new coverage report
       uses: actions/download-artifact@v2
       with:
         name: coverage-report
-        path: ./backend/coverage/previous
+        path: ./backend/new_coverage
 
-    - name: Compare coverage reports
+    - name: Install dependencies
       run: |
-        # Install jq to parse JSON
-        sudo apt-get install jq
-        CURRENT_COVERAGE=$(jq '.total.lines.pct' ./backend/coverage/coverage-final.json)
-        PREVIOUS_COVERAGE=$(jq '.total.lines.pct' ./backend/coverage/previous/coverage-final.json)
-        echo "Current Coverage: $CURRENT_COVERAGE%"
-        echo "Previous Coverage: $PREVIOUS_COVERAGE%"
-        if [ "$CURRENT_COVERAGE" -lt "$PREVIOUS_COVERAGE" ]; then
-          echo "Coverage decreased. Failing the job."
-          exit 1
+        python -m pip install --upgrade pip
+        pip install chardet
+
+    - name: Compare previous and new coverage reports
+      run: |
+        python <<EOF
+        import re
+        import chardet
+
+        def get_coverage_metrics(file_path):
+            with open(file_path, 'rb') as file:
+                raw_data = file.read()
+                result = chardet.detect(raw_data)
+                encoding = result['encoding']
+                
+                content = raw_data.decode(encoding)
+                # Adjusted regex to match the table header and extract the relevant percentages
+                match = re.search(r"All files\s*\|\s*([\d\.]+)\s*\|\s*([\d\.]+)\s*\|\s*([\d\.]+)\s*\|\s*([\d\.]+)", content)
+                if match:
+                    return list(map(float, match.groups()))
+            return []
+
+        def compare_coverage_reports(report1, report2):
+            metrics1 = get_coverage_metrics(report1)
+            metrics2 = get_coverage_metrics(report2)
+
+            print(f"Metrics Report 1: {metrics1}")
+            print(f"Metrics Report 2: {metrics2}")
+
+            if all(m2 >= m1 for m1, m2 in zip(metrics1, metrics2)):
+                if any(m2 > m1 for m1, m2 in zip(metrics1, metrics2)):
+                    print("Coverage improvement detected!")
+                else:
+                    print("Coverage remains the same.")
+            else:
+                print("Coverage deterioration detected!")
+                exit(1)
+
+        report1 = "./backend/coverage_report.txt"
+        report2 = "./backend/new_coverage/coverage_report.txt"
+
+        compare_coverage_reports(report1, report2)
+        EOF
+
+    - name: Reset to current commit
+      run: |
+        echo $GITHUB_SHA
+        git reset --hard $GITHUB_SHA
+    - name: Set up Formatting tools
+      run: npm install --save-dev prettier
+
+    - name: Format code in ./backend
+      run: |
+        prettier --check your-directory/**/*.js
+        # prettier --list-different ./backend
+        if [ $? -eq 0 ]; then
+          echo "No files need formatting."
         else
-          echo "Coverage is sufficient. Job succeeded."
+          echo "Files are formatting..."
+          prettier --write ./backend
+          echo "Differences found. Need to commit."
+          git add yourfile.js
+          git commit -m "Formatted code with Prettier"
+          git push origin main
         fi
+    # - name: Check code formatting
+    #   run: npm run format:check
+    #   working-directory: ./backend
 
-    - name: Check code formatting
-      run: npm run format:check
-      working-directory: ./backend
+    # - name: Format code
+    #   if: failure()
+    #   run: npm run format
+    #   working-directory: ./backend
 
-    - name: Format code
-      if: failure()
-      run: npm run format
-      working-directory: ./backend
-
-    - name: Commit formatted code
-      if: failure()
-      env:
-        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
-      run: |
-        git config --local user.email "github-actions[bot]@users.noreply.github.com"
-        git config --local user.name "github-actions[bot]"
-        git commit -am "style: auto format code"
-        git push
-
-    - name: Cleanup
-      run: echo "Cleaning up..."
+    # - name: Commit formatted code
+    #   if: failure()
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
+    #   run: |
+    #     git config --local user.email "github-actions[bot]@users.noreply.github.com"
+    #     git config --local user.name "github-actions[bot]"
+    #     git commit -am "style: auto format code"
+    #     git push
